### ISSUE TITLE
Screenshot on readme please

### ISSUE THREAD

**Issue by ghost** [McSinyx/axuy#3]
i would like to see a preview before downloading, i you could upload please :)

**Comment by McSinyx** [comment]
Hi and thank you for your interest in axuy!  f04a2ef34e90157142514f3bc111ffe6969a63f9 has just added a pointer to a Youtube playlist, but since you asked for screenshots, here's one:
![axuy](https://user-images.githubusercontent.com/13689192/85820832-57455280-b7a1-11ea-84c5-b049abfc2098.png)
